# Generated by Django 5.2.4 on 2025-07-29 09:16

import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=theme.models.Profile.get_default_avatar, upload_to='profile_avatars'),
        ),
    ]
